# FreeCash (FCH) Solo
rpc:
  host: "127.0.0.1"
  port: 8332
  user: "fchrpc"
  password: "FreecashSoloAutoRpc_ChangeMeIfPublic"
  timeout: 30

pool:
  payout_address: "FCHANGE_ME_GETNEWADDRESS"
  stratum_port: 3333
  stratum_host: "0.0.0.0"
  start_difficulty: 256
  job_interval: 25
  payout_threshold: 10.0

monitor:
  host: "0.0.0.0"
  port: 5050

logging:
  level: "INFO"
